### ISSUE TITLE
Disable unwanted modules by default

### ISSUE THREAD

**Issue by RadekCap** [thinkingrock-gtd/tr-pc#64] opened 2023-01-16 10:02 UTC
By #61 we probably introduced loading of some modules. When you run application from the latest source code, the message box appear with warning:

`Warning - could not install some modules: JSch Agent Proxy library - The module named com.jcraft.jsch was needed and not found.`
` HTML Validation - The module named org.apache.commons.logging was needed and not found.`
` Mylyn Support Utilities - The module named org.eclipse.mylyn.commons.net was needed and not found.`
` Mylyn Support Utilities - The module named org.eclipse.mylyn.tasks.core was needed and not found.`
` Mylyn Support Utilities - The module named org.eclipse.core.jobs was needed and not found.`
` Mylyn Support Utilities - The module named org.eclipse.mylyn.wikitext.core was needed and not found.`
` Mylyn Support Utilities - The module named org.eclipse.equinox.common was needed and not found.`
` Mylyn Support Utilities - The module named org.eclipse.core.runtime was needed and not found.`
` Local Tasks - The module named org.eclipse.mylyn.tasks.core was needed and not found.`
` Local Tasks - The module named org.eclipse.equinox.common was needed and not found.`
` Local Tasks - The module named org.eclipse.core.runtime was needed and not found.`
` Bugzilla - The module named org.eclipse.mylyn.commons.net was needed and not found.`
` Bugzilla - The module named org.eclipse.mylyn.bugzilla.core was needed and not found.`
` Bugzilla - The module named org.eclipse.mylyn.tasks.core was needed and not found.`
` Bugzilla - The module named org.eclipse.equinox.common was needed and not found.`
` Bugzilla - The module named org.apache.commons.httpclient was needed and not found.`
` Bugzilla - The module named org.eclipse.core.runtime was needed and not found.`
` Native Execution - The module named com.jcraft.jsch was needed and not found.`
` TextMate Lexer - The module named com.google.gson was needed and not found.`
` LSP Client - The module named com.google.guava was needed and not found.`
` LSP Client - The module named com.google.gson was needed and not found.`
` Git Client Library - The module named org.eclipse.jgit was needed and not found.`
` Git Client Library - The module named com.jcraft.jsch was needed and not found.`
` Git - The module named org.eclipse.jgit was needed and not found.`
` 10 further modules could not be installed due to the above problems.`

It appears just only one, it's skippable and never occurs again. I'm not sure if this is worth to solve but a new collaborators could be a little bit scared but his huge warning :)

![Screenshot from 2023-01-16 10-54-42](https://user-images.githubusercontent.com/6508800/212651228-b42017c1-5813-4153-bba1-03f37123ce14.png)

**Comment by ursjoss** [comment] 2023-01-16 11:57
Could probably be solved in context of ticket #57. could we treat this ticket as duplicate and you paste your findings there?

**Comment by RadekCap** [comment] 2023-01-16 12:39
It probably could be solved there but this is something that could discourage contributors so I've marked it as a bug so it'll will have a little higher priority.

**Comment by RadekCap** [comment] 2023-01-16 19:00
During the first start after clean compilation, and after modules warning, another dialog appears. This one:

![Image 16 01 2023 at 19 56](https://user-images.githubusercontent.com/6508800/212749298-c58d1c9b-a1eb-48c9-8f65-bc3579324c71.jpeg)

We should probably hide it as well. Or, maybe better, understand how it's working and use it the next time during the new release.

**Comment by ursjoss** [comment] 2023-01-16 20:33
:-) This pop-up is the result from fixing the issue of #60. With the fix from PR #61, the messages from the [endpoint](https://trgtd.com.au/messages.xml) are downloaded correctly by the `MessageChecker` and passed on to the `MessageParser`. The last check-date is cached, but since you have a clean repo (as you describe it after cleaning it), the code considers the check to be the first one. In this case, all valid messages are displayed. Currnelty, there is exactly one message not commented out. It is therefore displayed once (unless you clean again).

See the message here:
https://github.com/thinkingrock-gtd/tr-pc/blob/4b8f1078d6c8fd0a8d34e59c029897729b4601ba/modules/au.com.trgtd.tr.task.messages/test/unit/src/au/com/trgtd/tr/task/messages/messages.xml#L3

It is true, that we should not show that outdated message once we release a version 4.0.0. Until then, I don't mind. To not show the version, @clairelema should remove it from the XML.

**Comment by ursjoss** [comment] 2023-01-17 22:32
I found a [link](https://stackoverflow.com/questions/18545208/netbeans-could-not-install-some-modules) to an article stating that those symptoms may be caused by an outdated netbeans cache. Deleting the cached files may resolve it.

After having deleted my netbeans cache (on my linux system `~/.cache/netbeans/16/`), I have not had the issue anymore. Let's see if it pops up in the near future.

**Comment by RadekCap** [comment] 2023-01-18 14:08
Unfortunately, it's still present on my RHEL system after cache deletion.

**Comment by ursjoss** [comment] 2023-03-06 16:54
@RadekCap We might be able to close it now, what do you think?

**Comment by RadekCap** [comment] 2023-03-06 17:05
Yes

**Closed** 2023-03-06 17:05 UTC
Labels: bug
